version: '3.8'

services:
  
  mongo:
    container_name: mongo_db
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_DB_HOST=mongo
      - MONGO_DB_NAME=mongo_db

  postgres:
    container_name: postgres_db
    image: postgres
    ports:
      - '5432:5432'
    # volumes:
    #   - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=scrapy_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  mysql:
    image: mysql
    container_name: mysql_db
    cap_add:
      - SYS_NICE
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=scrapy_db
      - MYSQL_ROOT_PASSWORD=mevr1k1234
      # - MYSQL_ALLOW_EMPTY_PASSWORD=true
    restart: always
      
  
  # redis:
  #   image: redis/redis-stack:latest
  #   container_name: redis_server
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #   - '6379:6379'