"""medicin data table 

Revision ID: 851bafcf2a4e
Revises: 
Create Date: 2025-09-08 16:43:39.198668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851bafcf2a4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('generic_name', sa.String(length=500), nullable=True),
    sa.Column('strength', sa.String(length=200), nullable=True),
    sa.Column('dosage_form', sa.String(length=200), nullable=True),
    sa.Column('manufacturer', sa.String(length=500), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('pack_price', sa.Float(), nullable=True),
    sa.Column('strip_price', sa.Float(), nullable=True),
    sa.Column('pack_info', sa.Text(), nullable=True),
    sa.Column('indications', sa.Text(), nullable=True),
    sa.Column('composition', sa.Text(), nullable=True),
    sa.Column('mode_of_action', sa.Text(), nullable=True),
    sa.Column('dosage', sa.Text(), nullable=True),
    sa.Column('side_effects', sa.Text(), nullable=True),
    sa.Column('contraindications', sa.Text(), nullable=True),
    sa.Column('precautions', sa.Text(), nullable=True),
    sa.Column('interaction', sa.Text(), nullable=True),
    sa.Column('overdose_effects', sa.Text(), nullable=True),
    sa.Column('pregnancy_category', sa.Text(), nullable=True),
    sa.Column('storage_conditions', sa.Text(), nullable=True),
    sa.Column('drug_classes', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('pack_image_url', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_medicine_manufacturer', 'medicines', ['manufacturer'], unique=False)
    op.create_index('idx_medicine_scraped', 'medicines', ['scraped_at'], unique=False)
    op.create_index('idx_medicine_search', 'medicines', ['name', 'generic_name'], unique=False)
    op.create_index(op.f('ix_medicines_brand_id'), 'medicines', ['brand_id'], unique=True)
    op.create_index(op.f('ix_medicines_generic_name'), 'medicines', ['generic_name'], unique=False)
    op.create_index(op.f('ix_medicines_manufacturer'), 'medicines', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_medicines_name'), 'medicines', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicines_name'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_manufacturer'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_generic_name'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_brand_id'), table_name='medicines')
    op.drop_index('idx_medicine_search', table_name='medicines')
    op.drop_index('idx_medicine_scraped', table_name='medicines')
    op.drop_index('idx_medicine_manufacturer', table_name='medicines')
    op.drop_table('medicines')
    # ### end Alembic commands ###
